### ISSUE TITLE
Member responses not being sent to channel

### ISSUE THREAD

**Issue by Nikralx** [BitQuote/AwesomeBot#101]
Setup channel to have Deleted messages, banned member notifications, left members, and new members sent. Only new members is being sent by bot.

**Comment by BitQuote** [comment]
Try re-selecting the channel. Ensure that the bot has permission to send messages in the channel you selected.

**Comment by Nikralx** [comment]
I have tried re-selecting, and it does have persmission because it has posted member online info there before.
