### ISSUE TITLE
Bug: Adding profile field with empty value makes it hard to delete

### ISSUE THREAD

**Issue by Blazeflack** [BitQuote/AwesomeBot#106]
If you add a profile field with an empty value, then you can't delete it afterwards.
Example:

`!profile Test|` -> New profile field "Test" added with empty value
`!profile Test|.` -> Should delete "Test" field, but instead you get this: "I didn't have anything for Test in the first place."

In order to delete it you have to overwrite the field with a value first, and then delete it:
```
!profile Test|NewValue
!profile Test|.
```

I'm thinking the !profile command should not accept empty values to begin with.

**Comment by hucota7** [comment]
#107 should resolve this
