### ISSUE TITLE
Can't access maintainer console...?

### ISSUE THREAD

**Issue by Rotsuoy** [BitQuote/AwesomeBot#113]
I was able to access the admin console with `config <servername>` but when I tried using just `config` like it suggests I do on the [configuration page](https://github.com/BitQuote/AwesomeBot/wiki/Configuration), nothing happens. Not to mention, I've been unable to search for any suggestions or alternatives around the problem. Is it possible that for some reason I'm not considered a maintainer even though I was the one that added the bot to the server and am owner of said server? If so, is there a way I can change this?

**Comment by tinytaco8** [comment]
Fixed in Discord support, bot had incorrect user ID set :)
