### ISSUE TITLE
Extension works during test but not in server

### ISSUE THREAD

**Issue by xMarok** [BitQuote/AwesomeBot#114]
I wrote a simple extension that adds a role to every member on the server. In the output log of the extension builder I can see it add the role to every member, but when the command is actually used on the server it doesn't work. I should mention that I have over 4000 users on the server, so I'm not sure if there's just too many or something.

```
var myRole = svr.roles.getByName("Member");

for (var key in svr.members) {
  myRole.add(key);
}

ch.sendMessage("Added roles.");
```

It does output "Added roles.", so I know the command is being run.

Just as a test, I added `ch.sendMessage(key);` inside my for loop, and doing that actually made it add the role to about 75% of the users on the server.

**Comment by xMarok** [comment]
Well, while I was fixing up the code and adding a few other things, I ran the above multiple times for testing purposes, and now everyone has the proper role. Maybe it's just some kind of Discord limit for how fast/many roles can be added?

**Comment by pedall** [comment]
Can you publish the extension please? :)

**Comment by xMarok** [comment]
@pedall 

Done. :)

It's under "unapproved submitted items" so make sure you check there.

**Comment by pedall** [comment]
Ty so much!!
