### ISSUE TITLE
Extension status and ratings

### ISSUE THREAD

**Issue by pedall** [BitQuote/AwesomeBot#124]
Sometimes Extensions that have been approved are still broken or not executable. It should be possible for admins to change the extension status to "working" or "needs fix" or whatever status you want to give. But bot admins should see if an extensions works before they waste a lot of time on trying and searching for errors.

and bot admins also should be able to rate extensions, so other users see what are the best extensions :-) (simple 5 star system or thumbs up would be enough i guess)

Both status and rating should be shown directly next to the title of an extension so you can see it without going in details.

**Comment by Kays** [comment]
Extensions are community-based and AwesomeBot is not responsible for their usage. Also, sometimes, people just do not know how to install or use them properly which would give the extension a bad rep if they just set the status or rate it poorly.

**Comment by Kays** [comment]
v4 may have improvements to the extensions system, or a way to make things slightly more "official" but the current setup where extensions are managed by one person is not feasible to support this.
