### ISSUE TITLE
Tagreaction Command Not Following Dashboard Settings

### ISSUE THREAD

**Issue by ADKGamers** [BitQuote/AwesomeBot#130]
Hello,

Not sure what needs to be done as we've tried everything and no matter what we do Awesomebot still responds to a tag in a channel when "tagreaction  Responds when tagged without a command" is not set for that channel.  We even changed it to 'Admin Only' and it still responded to non admins tagging it. 

What will fix this issue?  Other that this little hiccup everything is good so far, just wish we could get that tagging working (or not working rather in this case). 

Thanks! :)

**Comment by BitQuote** [comment]
Cannot reproduce.

**Comment by ADKGamers** [comment]
It appears that it's sporadic when it does it.  I haven't seen it happen within the last day though.
