### ISSUE TITLE
AwesomeBot sometimes not responding to commands

### ISSUE THREAD

**Issue by Deakula** [BitQuote/AwesomeBot#138]
There is an issue with extensions where in some cases, if AwesomeBot deletes a message that contains an AwesomeBot command (such as the !say command), the command will not execute. 

Suggestion: prioritize commands over extensions so that a command first executes before an extension listening for the command does.

**Comment by BitQuote** [comment]
Cannot reproduce.

**Comment by Deakula** [comment]
Invalid confirmed; permission issues.
