### ISSUE TITLE
10 minutes between rss fetches is too long

### ISSUE THREAD

**Issue by mneko** [BitQuote/AwesomeBot#139]
It would be nice to be able to set how often it checks for rss feed items. I'm with a group using it as a reddit moderator chat, and being able to see new reports and stuff sooner than every 10 minutes would be awesome.

**Comment by BitQuote** [comment]
Unfortunately, 10 minutes is the best we can do for a bot with over 7000 servers. Self-hosting is probably the best solution for this.
