### ISSUE TITLE
instructions unclear - how are messages converted to points? 

### ISSUE THREAD

**Issue by b1gh** [BitQuote/AwesomeBot#149]
By viewing people's profiles it appears it's not 1:1 (for example, a user had over 800 messages for the week but is only at 300 points and hence the rank that corresponds to that).

Also what does "bad" constitute in regards to having points removed by the bot? Is this definable? 

Cheers!

**Comment by Blazeflack** [comment]
You get 1 point per 10 messages and 5 minutes in a voice channel.

**Comment by BitQuote** [comment]
This is a question, not an issue. Ask questions on our Discord server next time please!
