### ISSUE TITLE
Nuke doesn't work as displayed in help or wiki -- Conflicting syntax

### ISSUE THREAD

**Issue by dylanh724** [BitQuote/AwesomeBot#155]
> Deletes messages in a channel, all or from a user

But when AwesomeBot tells me how to use the command,

`Make sure to use the syntax nuke <no. of messages> [<username>]`

So how do I delete messages in a channel, and how do I delete ALL messages from the channel?

**Comment by BitQuote** [comment]
It means "messages from all users or messages from one user". Perhaps that should be clarified.

**Comment by Chris92de** [comment]
I updated the Wiki page to clarify this.
