### ISSUE TITLE
Awesome-Token

### ISSUE THREAD

**Issue by CPVPLachlan** [BitQuote/AwesomeBot#156]
Hi, 
I have not gotten the email regarding the awesome-token for about 3 weeks (I think), I've checked spam, trash, etc.

Thanks for your help,
TheCraftingHero

**Comment by BitQuote** [comment]
We no longer require an AwesomeBot token: 
https://github.com/BitQuote/AwesomeBot/commit/d8c7bc35e0289d1aec6642e46a66cca60046ae0c
https://github.com/BitQuote/AwesomeBot/commit/58e8977542f2e632bdfd20dddb6c1e49ced6d891

**Comment by CPVPLachlan** [comment]
Thanks so much @BitQuote !
