### ISSUE TITLE
Request: Custom chat message command

### ISSUE THREAD

**Issue by newb23** [BitQuote/AwesomeBot#159]
I've been looking around the base bot and in the extensions, I do not see an option of adding a custom response for say customer providing a bad report, and rather than typing the whole phrase themselves, an admin could type:

!bugreportinfo

and the bot would type to the channel 

"For reporting bugs, please refer to the bug reporting outline "URLhere". Please note, any missing information may delay us in our ability to assist you."

Something akin to these, for example: https://github.com/Kwoth/NadekoBot/wiki/Custom-Reactions

Thank you!

**Comment by BitQuote** [comment]
Create a tag command: `!tag <name>|<content>|command`
This will make `!<name>` return `<content>`
