### ISSUE TITLE
[request] Allow Administrators to reset AwesomePoints to 0 with !points clear

### ISSUE THREAD

**Issue by ElPared** [BitQuote/AwesomeBot#173]
Or some other command.  I feel this would be a good tweak to AwesomePoints as I could reset them to 0 every month X amount of time and treat them like a Ladder of sorts.  Points are very handy to track user participation and it's more fun to use them than just !messages, plus being able to reset gives newer users a shot at the same rewards as older users (We want to facilitate in-game rewards for lotteries and things like that but it seems unfair to do so when older users can hoard points and just buy the pot).

**Comment by mistmurk** [comment]
Currently, points are global, so this would mess up other servers. In v4, however, this will be possible.

**Comment by ElPared** [comment]
oh I see.  That explains why users leave the server still have points if they come back.

Side note:  I'm relatively new to GitHub, how do I add labels to something?

**Comment by Kays** [comment]
Only the owner and collaborators can set labels.
