### ISSUE TITLE
Bot saves .json files as a single line

### ISSUE THREAD

**Issue by FoolMeOnce** [BitQuote/AwesomeBot#175]
If the bot saves a .json file, it's written as a single line instead of being 'pretty printed' JSON.
This makes it somewhat difficult to edit a config file after the bot has touched it.

**Comment by FoolMeOnce** [comment]
I submitted a PR to address the issue: https://github.com/BitQuote/AwesomeBot/pull/174

**Comment by Kays** [comment]
See PR for comments.
