### ISSUE TITLE
bug? - "config server_name_here" is not resulting in any response - tried after AwesomeBot got back online

### ISSUE THREAD

**Issue by poorronin** [BitQuote/AwesomeBot#189]
i've tried @mention'ing directly to the bot, using plain text, even adding AwesomeBot to a completely new server and starting fresh with a single-word server name. Thoughts?

**Comment by Poeschl** [comment]
You need to pm the bot directly with config <server name>. But its currently not possible, since #178 is still open.

**Comment by poorronin** [comment]
@Poeschl - thanks - i was hoping the all-clear from status.awesomebot.xyz was an indicator that things were better - i'll check in later - thanks again.

**Comment by Poeschl** [comment]
@poorronin You're welcome. I'm with you for the waiting :walking_man:
