### ISSUE TITLE
Unresponsive in PMs, Intermittently Offline in Server

### ISSUE THREAD

**Issue by RandomAnimeGamer** [BitQuote/AwesomeBot#191]
Not sure if these are caused by the same problem, but here's what I've been dealing with for about a week now.

Every once in a while, AwesomeBot keeps going offline in my server for some reason. During this time, anyone that joins doesn't get the default role that AwesomeBot would normally set them to (Since it's offline at the time).

Another problem is that I will type "config servername" (Where server name is my server's name) and it only responds with a link half the time. The other half is where it doesn't respond at all. Actually, it's not just when I type in config, it only really responds half the time (Or with large latency).

If there's anything I'm missing here, or if you need more information, please let me know! I'm sort of new to AwesomeBot, so if you ask for something please let me know how to get it. Thanks!

**Comment by tinytaco8** [comment]
This is an issue with v3.4, it will be fixed in the next AwesomeBot version (v4), thanks for your patience!
