### ISSUE TITLE
Simplify Web Interface by Having Multiple Rows

### ISSUE THREAD

**Issue by Shuttle099** [BitQuote/AwesomeBot#32]
![commandlst](https://cloud.githubusercontent.com/assets/2822125/15449680/b835e7c6-1f52-11e6-9c78-92bf6d1fa97a.png)

**Comment by tinytaco8** [comment]
Or make it collapsible and have basic descriptions of what they do next to each command

**Comment by BitQuote** [comment]
It is already collapsible, and descriptions are coming

**Comment by BitQuote** [comment]
Added in v3.3.21
