### ISSUE TITLE
Who actually participated and answered questions in the trivia game?

### ISSUE THREAD

**Issue by rrbailey89** [BitQuote/AwesomeBot#34]
I have an idea for my community that I think would be useful for others as well. The current setup for the trivia game is that once it is ended it will display a number that the community as a whole answered correctly. I would like this modified or maybe an option added to the initial trivia command that begins the game to make it so that it displays a breakdown of who answered how many questions correctly.

**Comment by BitQuote** [comment]
Added in v3.3.21
