### ISSUE TITLE
[Wiki Update] Updated Wiki to reflect v3.4 changes to Extentsions & new website structure

### ISSUE THREAD

**Issue by Birdgeek** [BitQuote/AwesomeBot#38]
Changes found [here](https://github.com/Birdgeek/AwesomeBotWiki).
More specifically [this commit](https://github.com/Birdgeek/AwesomeBotWiki/commit/be96501afabc6390e322c7c29cac3699ed263a0f) and  [this commit](https://github.com/Birdgeek/AwesomeBotWiki/commit/7c64e2c2f2142eb62a2277e4f8aa08a0920b6472).

**Comment by BitQuote** [comment]
Thanks, I'll copy that into the v3.4 wiki! :)
