### ISSUE TITLE
(NOT AN ISSUE) Suggestion

### ISSUE THREAD

**Issue by LoganDark2** [BitQuote/AwesomeBot#39]
You should allow people to create fully functional custom commands using (edited comment) Lua. You should allow the user to enter THEIR OWN code, make use of parameters and/or arguments, etc.

**Comment by jaw3l** [comment]
[Extensions](https://github.com/BitQuote/AwesomeBot/wiki/Extensions)
and there will be a Extension Builder in 3.4 branch..

**Comment by LoganDark2** [comment]
Well can it be in lua please
