### ISSUE TITLE
TypeError: base64.base64encoder is not a function

### ISSUE THREAD

**Issue by Loftless** [BitQuote/AwesomeBot#40]
Really stupid question, but I've been trying to fix this for hours, with no luck.

Any time I try to 'node start.js' I'm getting this error, and can't find a fix.

Anyone able to let me know why this keeps happening? Clearly I'm missing the reference, but can't figure out how to fix it.

Thanks in advance

**Comment by Loftless** [comment]
To fix this, I had to ensure the bot had no icon. This seemed to fix it.

I however then ran into:
`TypeError: Cannot read property 'members' of undefined
    at clearStatCounter (C:\Users\Loftless\Desktop\AwesomeBot-3.3.7p1\start.js:3008:45)`

That issue. I had to remove all references to clearStatCounter in order to fix it.

Obviously not idea, but it's a work-around for now I suppose.

**Comment by jaw3l** [comment]
Try to replace `encoder` instead of `base64encoder`. Afterwards it will look like `base64.encoder`.

**Comment by BitQuote** [comment]
@Loftless That would lead to data problems down the road, but should work for now.
@jaw3l is correct about base64encoder

Both of these are fixed in v3.4
