### ISSUE TITLE
Website downtime

### ISSUE THREAD

**Issue by LoganDark2** [BitQuote/AwesomeBot#41]
The website is offline, but the bot still works and sends auth links that lead to this page.

![Page](https://cloud.githubusercontent.com/assets/4723091/16085009/84ebcad0-32cf-11e6-8773-ea979ccfa09e.png)

**Comment by BitQuote** [comment]
We are aware of the *outage*, which is why the [status page](http://status.awesomebot.xyz/) says "Major Outage". In the future, please report outages on [our Discord server](http://discord.awesomebot.xyz/) instead of on GitHub.

**Comment by LoganDark2** [comment]
Oh, sorry, turns out the link ON THE WIKI STATUS PAGE leads to a 503 ERROR, yeah, that page is very readily accessible.

**Comment by LoganDark2** [comment]
THAT COMMUNICATES THE STATUS EXACTLY THANK YOU VERY MUCH

**Comment by jaw3l** [comment]
![quickmemo _2016-06-15-18-45-30](https://cloud.githubusercontent.com/assets/16852455/16086817/83207fd4-3329-11e6-8c28-7b5dbb4963c3.png)....  Please stop this insanity
