### ISSUE TITLE
Lua extension builder

### ISSUE THREAD

**Issue by LoganDark2** [BitQuote/AwesomeBot#42]
Can you make an extension builder you can program in Lua? And possible a few other programming languages as well? Some of us aren't very fluent in JS.

**Comment by LoganDark2** [comment]
This is a request.

**Comment by BitQuote** [comment]
JS is extremely easy to learn, and it's easy to run in a NodeJS VM. Also, you already requested this in another issue thread so there was no need to make another issue.

**Comment by LoganDark2** [comment]
Guess what, I don't care.

Might as well stop using your bot anyway. It was a nice try. Turns out this in fact IS too good to be true.

**Comment by rrbailey89** [comment]
Wtf..
