### ISSUE TITLE
Awesomebot 3.4 Awesome Token?

### ISSUE THREAD

**Issue by Loftless** [BitQuote/AwesomeBot#43]
Awesome help (pun intended) with the previous issues with the 3.3.7p1 release. 3.4 does look to fix all dependency issues, hooray!

With 3.4 I am getting:
`[2016-06-17 00:35:53 UTC] [ERROR] [General] Unauthorized self-hosted AwesomeBot running, exiting. Please see https://github.com/BitQuote/AwesomeBot/wiki/Setup#getting-started`
Which I assume has to do with the 'Awesome Token' addition. Obviously the getting started hasn't been updated since this is not the master release yet.

Just looking to see if there is a way to get that as of now? or is this something we will have to wait for the master release for?

Great bot, love the ease of use, and the official bot has been fantastic. Thanks!

EDIT: Oh, not trying to be impatient or rude. The 3.3.7p1 release won't compile because of the previous dependency issues, and is also having issues with the member functions. That's the only reason I'm messing around with 3.4 as a code base.

**Comment by BitQuote** [comment]
Starting with v3.4, you will have to apply for an AwesomeBot Token if you want to self-host the bot. Fill out the form [here](http://self-host.awesomebot.xyz/) and I will evaluate your response before sending you a token via email.
