### ISSUE TITLE
Config screen doesnt open

### ISSUE THREAD

**Issue by aycgit** [BitQuote/AwesomeBot#59]
If i go to bot.awesomebot.xyz it tells. Me to run the config command
When i do that i get a link with a auth token but when i click the link it just works as a normal bot.awesomebot.xyz link, ive very recently installed awesomebot

Does someone know a fix for this? I would like to be able to access the config

**Comment by BitQuote** [comment]
Are you using the Android app? It has a problem with question marks in any URL. Make sure you're navigating to the entire URL in your browser.

**Comment by aycgit** [comment]
1: why invalid
2: no i was using ios and pasting the link in safari
