### ISSUE TITLE
New Command

### ISSUE THREAD

**Issue by Caius-Scipio** [BitQuote/AwesomeBot#62]
I'd like to see a command for AwesomeBot to be able ti pull a list of which members have been given what role on a specified server. For example:
!rollcall <server>
AwesomeBot responds with:
>Role A
MemeberX
>Member Y
>Member Z
Role B
>Member Y
>Menber Z
Role C
>Member Z

**Comment by BitQuote** [comment]
Will be added as output for `role` without parameters in tonight's or tomorrow night's update.

**Comment by Caius-Scipio** [comment]
You guys are awesome!
