### ISSUE TITLE
New Command for AwesomeBot

### ISSUE THREAD

**Issue by Caius-Scipio** [BitQuote/AwesomeBot#63]
Discord had limited options when using it while not on a PC. Many options available on a computer are not available while using a smartphone or being mobile. I'd like to see AwesomeBot be able to grant channel or server permissions to members or roles. For example, to give someone permission to send a message on a channel:
!permission <server> <channel> <member> send messages <- toggle on/off
And that would give the member access to send messages on the specified channel on the specified server. Or alternatively, instead of a member, it could be a role which would be more useful for myself.

**Comment by BitQuote** [comment]
`perm` command will be added in tonight's or tomorrow night's update.

**Comment by Caius-Scipio** [comment]
You guys are awesome!
