### ISSUE TITLE
Delete store keys

### ISSUE THREAD

**Issue by Kays** [BitQuote/AwesomeBot#65]
`writeStore` allows saving key/value, but I can't find a way to delete a key. I can set the value to null but the key persists. It's not a big problem but that would be taking up unnecessary space in my opinion.

`https://github.com/BitQuote/AwesomeBot/blob/master/bot.js#L5681`

**Comment by BitQuote** [comment]
Fixed: https://github.com/BitQuote/AwesomeBot/wiki/Extensions#deletestore
