### ISSUE TITLE
Nevermind

### ISSUE THREAD

**Issue by Zyrixion** [BitQuote/AwesomeBot#70]
No, seriously.  user.roles returns a completely unusable object, that I'm not even sure what to do with because the details of the object it returns are noted nowhere in the api, and aforementioned object refuses to function or compare with anything, or allow any other api function call (or anything else, either) to pull values from it.  Or otherwise, I have no idea how to pull data from it, because its structure is completely hidden.

Additionally, if role IDs exist, which by all manners of trying to work with them they do not, where the hell are you pulling them from/do I even find them?

**Comment by BitQuote** [comment]
Heh.
