### ISSUE TITLE
Escape markdown characters in names

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [BitQuote/AwesomeBot#71]
`_` > `\_`
`*` > `\*`
`**` > `\**`
``  ` `` > `` \` ``
etc.

Because one asterisk can break all formatting in message:
![image](https://cloud.githubusercontent.com/assets/10401817/17084658/90a07f1e-51ed-11e6-9747-aa09728960fc.png)

**Comment by BitQuote** [comment]
Fixed.
