### ISSUE TITLE
Add Timeout to Select Menu

### ISSUE THREAD

**Issue by Kays** [BitQuote/AwesomeBot#74]
Select menus should not need to persist for longer than 10 seconds and auto-quit so people don't have to enter "quit" all the time. Usually not a problem but it is a common case of people to not care for the results and decide to do another command only to be roadblocked by select menu.

Alternatively (or also include), another approach is to add an additional check to restrict the check/run of the select menu to only run when the message content/suffix is numeric and within the range of 0 - selectmenu[chan].max. Either way, it's better than roadblocking all commands in a channel until select menu is resolved.

**Comment by BitQuote** [comment]
Fixed in v4!
