### ISSUE TITLE
Tags saving is broken

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [BitQuote/AwesomeBot#75]
Tags adding through console is broken

![image](https://cloud.githubusercontent.com/assets/10401817/17277263/a6fe00ee-5768-11e6-94fd-88feb659b8f8.png)

will saved like...

![image](https://cloud.githubusercontent.com/assets/10401817/17277255/8ea9e5a8-5768-11e6-8356-c4b1c47120a4.png)

**Comment by BitQuote** [comment]
Fixed.
