### ISSUE TITLE
List does not create IDs for the newly created list items

### ISSUE THREAD

**Issue by pedall** [BitQuote/AwesomeBot#77]
When creating List items via the !list command, the newly created items wont have an ID that can be used to remove an Item.

![list bug awesomebot](https://cloud.githubusercontent.com/assets/20089354/17289865/d457744e-57db-11e6-87c5-c5392b786c64.png)

**Comment by pedall** [comment]
why is it invalid? ;-)

**Comment by BitQuote** [comment]
Use the index of the item (starting from 0).
