### ISSUE TITLE
Request: !role command should be useable for multiple roles at once

### ISSUE THREAD

**Issue by pedall** [BitQuote/AwesomeBot#79]
It would be nice if the !role command could be used to assign multiple roles at once.

e.g. on our server (gaming community) we created gaming roles for certain activities

At the moment users have to add each role one by one:
!role division_DZ
!role division_underground
!role division_incursion
etc.

 It would be nice if a user could type !role divisionroles (what would be a bundle of rules) and he would get all roles in that bundle (e.g. division_DZ, division_underground, division_incursion)

Another option would be to assign roles via selection. E.g. a user types !roles and the bot asks which roles should be applied:

[1] division_DZ
[2] division_underground
[3] division_incursion

And the user could reply with: !role 1,3 and would be assigned role 1 and role 3.

**Comment by BitQuote** [comment]
An extension would be able to do this.

**Comment by pedall** [comment]
I'll try to create one but I have no clue about JavaScript ;)
