### ISSUE TITLE
Allow timer extensions to be called manually with command too

### ISSUE THREAD

**Issue by Blazeflack** [BitQuote/AwesomeBot#87]
I am in a situation where I lack the ability to manually call a timer based extension.

I am writing an extension which needs to store some information that I have to supply it through a command, but the extension should also periodically do something with this information.

In an ideal world I would separate the extensions, but since one extension cannot access the store of another extension, I have to keep the code in a single extension. This leaves me to the problem where I am forced to make it a command extension so I can supply the needed information. I will then have to remind myself to use this command periodically, instead of having it execute on a timer.

**Comment by BitQuote** [comment]
This shouldn't be an issue in v4.
