### ISSUE TITLE
Add "store" for entire server

### ISSUE THREAD

**Issue by Blazeflack** [BitQuote/AwesomeBot#89]
It would be really awesome if we had a way to store information that should be available to all extensions on the server.

The storage in an extension is rather volatile, as any update to this extension causes the "store" to be completely erased, and there is currently no way to make a backup of the store in an extension.

If a "store" could be added for the server, then it should preferably be visible in some capacity through the admin console, and it should be possible to import/export it for backup.

**Comment by BitQuote** [comment]
Extensions can access all server data in v4, including `store` for other extensions.
