### ISSUE TITLE
the main file is 9.7k lines

### ISSUE THREAD

**Issue by GusCaplan** [BitQuote/AwesomeBot#98]
Take a look around
Think about what you are doing here

**Comment by BitQuote** [comment]
v4.

**Comment by macdja38** [comment]
Not sure why this is closed. This is clearly still an issue.

**Comment by tinytaco8** [comment]
Alright, but it's being worked on so there's no need for the issue to be open?

**Comment by hucota7** [comment]
While it is technically an issue, it is an issue for the developers, and maybe 0.1% of users who self-host and modify code. As it is actively being addressed with v4, there's no need for this issue to be open. There's nothing short of a rewrite that will address the issue, and that's exactly what v4 is.

**Comment by GusCaplan** [comment]
the general rule of issues is that they stay open until the issue is confirmed fixed, just sayin'

**Comment by Programmix** [comment]
http://i.imgur.com/JIQTwah.png

**Comment by Programmix** [comment]
![image](https://cloud.githubusercontent.com/assets/13167687/21585969/779945b2-d07f-11e6-89bd-b24fac8aa277.png)

**Comment by Oliy1492** [comment]
This is clearly gr8 m8

**Comment by TheEpTic** [comment]
10/10

**Comment by Oliy1492** [comment]
- IGN would version 3 again

**Comment by deansheather** [comment]
Ive come to realise that what I really need in my life is real time traffic information for my route to find cat

**Comment by AlexFlipnote** [comment]
Best issue so far
